batch_size: 128
dataset: dd
dropout: 0.5
epochs: 100
experiment_name: baseline_graphsage
hidden_dim: 64
lr: 0.001
model: graphsage
num_layers: 6
rewiring: none
save_model: false
seed: 42
weight_decay: 0.0005
