batch_size: 128
dataset: enzymes
dropout: 0.5
epochs: 100
experiment_name: ricci_curvature_gcn
hidden_dim: 64
lr: 0.001
model: gcn
num_layers: 2
rewiring: curvature
save_model: false
seed: 37
weight_decay: 0.0005
