batch_size: 512
dataset: qm9
dropout: 0.2
epochs: 30
experiment_name: virtual_nodes_gat
hidden_dim: 64
lr: 0.01
model: gat
num_layers: 8
rewiring: virtual_nodes
save_model: false
seed: 42
weight_decay: 0.0005
