batch_size: 128
dataset: zinc
dropout: 0.2
epochs: 30
experiment_name: virtual_nodes_gcn
hidden_dim: 64
lr: 0.01
model: gcn
num_layers: 2
rewiring: virtual_nodes
save_model: false
seed: 42
weight_decay: 0.0005
